name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      testing:
        description: Use fcitx5-js testing release
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install dependencies
        run: |
          curl -LO --output-dir cache https://github.com/fcitx-contrib/fcitx5-js/releases/download/${{ inputs.testing == true && 'testing' || 'latest' }}/fcitx5-js.tgz
          curl -LO --output-dir cache https://github.com/fcitx-contrib/fcitx5-config-vue/releases/download/latest/fcitx5-config-vue.tgz
          npm i -g pnpm
          pnpm i

      - name: Lint
        run: |
          pnpm run lint
          pnpm run check

      - name: Build
        run: |
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist

  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-24.04}
          - {os: ubuntu-24.04-arm}
          - {os: macos-26}
          - {os: windows-2025}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist

      - name: Install dependencies
        run: |
          curl -LO --output-dir cache https://github.com/fcitx-contrib/fcitx5-js/releases/download/${{ inputs.testing == true && 'testing' || 'latest' }}/fcitx5-js.tgz
          curl -LO --output-dir cache https://github.com/fcitx-contrib/fcitx5-config-vue/releases/download/latest/fcitx5-config-vue.tgz
          npm i -g pnpm
          pnpm i
          npx playwright install
          npx playwright install-deps

      - name: Test
        run: |
          pnpm run test

  release:
    if: ${{ github.ref == 'refs/heads/master' || inputs.testing == true }}
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: fcitx5-online

      - name: Package
        run: |
          zip -r fcitx5-online.zip fcitx5-online

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ inputs.testing == true && 'testing' || 'latest' }}
          prerelease: true
          title: ${{ inputs.testing == true && 'Testing Build' || 'Nightly Build' }}
          files: |
            fcitx5-online.zip

      - name: Delete testing release
        if: ${{ inputs.testing != true }}
        run: gh release delete testing --yes --repo fcitx/fcitx5-online || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
